# Generated by Django 5.1.7 on 2025-03-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('reseau', models.CharField(choices=[('Airtel', 'Airtel'), ('MTN', 'MTN')], max_length=10)),
                ('categorie', models.CharField(choices=[('Famille', 'Famille'), ('Professionnel', 'Professionnel'), ('Autres', 'Autres')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
